### ISSUE TITLE
Some Mock Methods Missing for Elasticsearch 6

### ISSUE THREAD

**Issue by helloworldless** [ctron/de.dentrassi.elasticsearch.log4j2-mock#1]
I found this project through this fascinating thread: https://github.com/elastic/elasticsearch/issues/19415. I'm using Elasticsearch 6.5.1 and getting this error:

```text
NoClassDefFoundError: org/apache/logging/log4j/core/Configurator
  at org.elasticsearch.common.logging.Loggers.setLevel (Loggers.java: 133)
```

So I added the `log4j2-mock` dependency, and I see it resolved a few of the issues in `org.elasticsearch.common.logging.Loggers.setLevel`. But there are still a few methods Elasticsearch is trying to call which don't exist on the mock:

`Configuration#getLoggerConfig`
`LoggerConfig#setLevel`
`LoggerContext#updateLoggers`

I'm guessing that elasticsearch wasn't using these methods in v5, so that's why they're missing from `log4j2-mock`. Is that right?

**Comment by helloworldless** [comment]
Update: I was able to add the `org.apache.logging.log4j:log4j-core` dependency. It resolved the missing classes for ES and it doesn't seem to have caused any side effects.

**Comment by ctron** [comment]
Thanks for the update!

I stopped working with ES in version 5. So if you think adding those methods helps, I would be happy get merge a PR and release a new version!

If you think everything is fine by adding `log4j-core`, then I think it would be ok to close the issue.
